### ISSUE TITLE
Analyze the cosmwasm-std iterator feature usage

### ISSUE THREAD

**Issue by kerber0x** [White-Whale-Defi-Platform/white-whale-core#100]
Go through migaloo contracts and study if the iterator feature is needed for all the contracts.

At the moment, it is being imported everywhere as it is being inherited from the workspace. Removing it from where it isn't needed would decrease the wasm size.

**Comment by kaimen-sano** [comment]
Not entirely sure if it would decrease the wasm size, the wasm optimizer should remove dead code from the binary already.
Still a good exercise to do.
