### ISSUE TITLE
Pool network on Kujira FIN

### ISSUE THREAD

**Issue by silvermind** [White-Whale-Defi-Platform/white-whale-core#109]
## Use case

- expand WW to the Kujira Network https://kujira.app/ and include arbs with FIN https://fin.kujira.app/

## Proposal

Would it be generally possible to expand the WW migaloo-core to also work with the Cosmos SDK Blockchain Kujira?

FIN is their Central Limit Order Books (CLOB) Exchange and not an AMM. Would the architecture allow FIN to act as a "Pool network" as well?

**Comment by Sen-Com** [comment]
Hey @silvermind!

Thanks for reaching out. We are very much in favor of deploying a Liquidity Hub, which includes a pool network and a flash loan vault network, on Kujira. We are just waiting for the green light from the Kujira core team. Once we have that, we will put up an on-chain governance proposal. 


Best Regards

Sen Com
