### ISSUE TITLE
Add dev-dependencies as workspace dependencies

### ISSUE THREAD

**Issue by kerber0x** [White-Whale-Defi-Platform/white-whale-core#114]

**Comment by kaimen-sano** [comment]
There is currently no way to implement `dev-dependencies` in a `Cargo.toml` that defines a workspace. [this](https://doc.rust-lang.org/cargo/reference/workspaces.html#workspaces) page outlines the current allowed sections.

**Comment by kerber0x** [comment]
It is possible, see https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table.

So you define it as a "normal" dependency under `[workspace.dependencies]` but then import it under `[dev-dependencies]`

![Screenshot from 2023-02-28 11-43-48](https://user-images.githubusercontent.com/94062656/221844543-73e30596-3223-4552-8814-013d033420cb.png)
