### ISSUE TITLE
Check contract names when performing migrations

### ISSUE THREAD

**Issue by kerber0x** [White-Whale-Defi-Platform/white-whale-core#175]
If you want to report a security issue, please follow our security policy: `https://github.com/White-Whale-Defi-Platform/migaloo-core/blob/main/SECURITY.md`

---
## Improvement description

This will prevent accidentally migrating to other contracts.

---

### Additional context
Add any other context here, code snippets, json responses, screenshots and so on.

<details>
<summary>Code sample</summary>

```rust
```

</details>

<details>
  <summary>Logs</summary>

```
```

</details>

<details>
  <summary>Screenshots</summary>

```
```

</details>

**Comment by 0xFable** [comment]
Fixed in #195
