### ISSUE TITLE
feat: add emergency unbond

### ISSUE THREAD

**Issue by Sen-Com** [White-Whale-Defi-Platform/white-whale-core#193]

**Comment by Sen-Com** [comment]
This allows users to better manage their risk regarding their positions and unbonding periods.
Users can call the "emergency unbond" at any time during the unbonding process, however some of the tokens will be forfeited. These forfeited tokens will simply stay inside the pool and not be sent to the fee collector. In that sense it equates to a permanent "lock" of tokens inside the incentive contract. 

To calculate the formula of how many tokens the user will receive back and how many will stay inside the pool, use this formula:

emergency fee = 
the emergency fee is the percentage of LP tokens that become locked inside the incentive contract.
consequently the user can withdraw (1-emergency fee) tokens

**Comment by kerber0x** [comment]
Done in V2.
